name: yettel_homework
description: "Yettel homework"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^9.2.2
  get_it: ^8.0.0
  injectable: ^2.5.0
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.3

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
